#!/bin/bash
set -e
set -x 
ctr1=$(buildah from almalinux)
APP_VERSION=$(curl -Is  https://github.com/sigstore/cosign/releases/latest 2>&1 | grep location | sed 's#.*/tag/v\(.*\)#\1#g' | tr -d '\r' )
echo $APP_VERSION
echo "https://github.com/sigstore/cosign/releases/download/v${APP_VERSION}/cosign-${APP_VERSION}.x86_64.rpm"
buildah run "$ctr1" rpm -i "https://github.com/sigstore/cosign/releases/download/v${APP_VERSION}/cosign-${APP_VERSION}.x86_64.rpm"
buildah copy "$ctr1" ./entrypoint.sh /bin/entrypoint.sh
buildah run "$ctr1" chmod 777 /bin/entrypoint.sh
buildah run "$ctr1" useradd cosign -m -s /bin/bash
buildah config --entrypoint '["/bin/entrypoint.sh"]' "$ctr1"
buildah config --user cosign "$ctr1"
buildah commit $ctr1 auroranexus.smartstream-stp.com:5000/cosign
buildah rm $ctr1
set +x